import { ClerkProvider } from "@clerk/nextjs";
import { TRPCReactProvider } from "~/trpc/react";

// STYLES
import "~/styles/globals.css";
import MainLayout from "~/components/layout/Main";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <TRPCReactProvider>
          <MainLayout>{children}</MainLayout>
        </TRPCReactProvider>
      </html>
    </ClerkProvider>
  );
}
